#!/bin/sh

# git config core.hooksPath Env/GitHooks/
# ブランチ名取得
branch=$(git branch | grep ^* | sed -e 's/^\* //g' -e 's/^(no branch, rebasing //g' -e 's/)$//g')
ticket=$(git branch | grep ^* | egrep '#\d{4}' | perl -pe 's/.*(#\d{4}).*/\1/')

# ブランチ名が取れなかった場合
if [ ! $branch ]; then branch='unknown_branch'; fi
if [ ! $ticket ]; then ticket=''; fi

## プレフィックスとしてブランチ名をコミットメッセージに付与する
msg=$(cat $1)
echo "[$branch] $ticket $msg" > $1

